name: Django Build and Deploy

on:
  push:
    branches:
      - main  # Adjust this according to your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Adjust this to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust this to your requirements file path

    - name: Run Django migrations
      run: |
        python manage.py migrate

    - name: Run Django tests (optional)
      run: |
        python manage.py test  # Adjust this as per your test setup

    - name: Deploy to Linux server
      uses: appleboy/ssh-action@master
      with:
        host: 194.164.199.244
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        
        script: |
          cd /root/MyFan/
          git pull main origin
